package scalafix.internal.util
import org.typelevel.paiges.Doc

object DocConstants {
  val `|` = Doc.char('|')
  val `&` = Doc.char('&')
  val `.` = Doc.char('.')
  val `#` = Doc.char('#')
  val `(` = Doc.char('(')
  val `)` = Doc.char(')')
  val `[` = Doc.char('[')
  val `]` = Doc.char(']')
  val `{` = Doc.char('{')
  val `}` = Doc.char('}')
  val `=>` = Doc.text("=>")
  val `()` = Doc.text("()")
  val `*` = Doc.char('*')
  val L: Doc = Doc.char('L')
  val f: Doc = Doc.char('f')
  val `:` = Doc.char(':')
  val `@` = Doc.char('@')
  val `val`: Doc = Doc.text("val")
  val `var`: Doc = Doc.text("var")
  val `def`: Doc = Doc.text("def")
  val `type`: Doc = Doc.text("type")
  val `null`: Doc = Doc.text("null")
  val `this`: Doc = Doc.text("this")
  val `super`: Doc = Doc.text("super")
  val `extends`: Doc = Doc.text("extends")
  val `with`: Doc = Doc.text("with")
  val `forSome`: Doc = Doc.text("forSome")
}
