// DO NOT EDIT: this file is generated by build.sbt
package scalafix.internal.sbt

object ScalafixRuleNames {
  def all: List[String] = List(
    "DottyKeywords",
    "DisableSyntax",
    "NoFinalize",
    "NoValInForComprehension",
    "RemoveXmlLiterals",
    "LeakingImplicitClassVal",
    "VolatileLazyVal",
    "ProcedureSyntax",
    "ExplicitUnit",
    "DottyVolatileLazyVal",
    "DottyVarArgPattern",
    "NoInfer",
    "Sbt1",
    "ExplicitResultTypes",
    "ExplicitReturnTypes",
    "RemoveUnusedImports",
    "RemoveUnusedTerms",
    "NoAutoTupling",
    "Disable",
    "DisableUnless",
    "MissingFinal"
  )
}
