// DO NOT EDIT: this file is generated by build.sbt
package scalafix.internal.sbt

object ScalafixRewriteNames {
  def all: List[String] = List(
    "DottyKeywords",
    "NoValInForComprehension",
    "RemoveXmlLiterals",
    "VolatileLazyVal",
    "ProcedureSyntax",
    "ExplicitUnit",
    "DottyVarArgPattern",
    "Sbt1",
    "ExplicitReturnTypes",
    "RemoveUnusedImports",
    "NoAutoTupling"
  )
}
